[mypy]
python_version = 3.11
files = nautical_core.py,on-add-nautical.py,on-modify-nautical.py
show_error_codes = True
pretty = True
ignore_missing_imports = True
follow_imports = skip
no_implicit_optional = True
warn_redundant_casts = True
warn_unused_ignores = True
disable_error_code = union-attr,attr-defined,assignment,arg-type,return-value,operator
