"""Integrity checks for the developer golden-test registry.

These checks verify the remaining runner registry and the explicit allowlist
for direct-contract tests migrated out of the golden runner.
"""

import importlib
import unittest


GOLDEN_MODULE = "dev_tools.nautical_golden_tests"
RETIRED_CHARACTERIZATION_TESTS = frozenset(
    {
        "test_reconcile_candidate_discovery_is_narrow_and_deterministic",
        "test_reconcile_delayed_expiration_dry_run_converges_to_live_slot",
        "test_reconcile_empty_snapshot_is_authoritative",
        "test_reconcile_lifecycle_outcomes_preserve_retry_and_manual_review",
        "test_reconcile_planning_configuration_drift_is_partial",
        "test_reconcile_reuses_verified_live_recovery_child",
        "test_reconcile_snapshot_reuses_initial_chain_export",
        "test_prev_weekday_natural_text",
        "test_natural_interval_or_branches_keep_cadence_with_subject",
        "test_natural_compresses_repeated_within_variants",
        "test_natural_compresses_repeated_fall_on_variants",
        "test_recurrence_evaluator_owns_context_spec_and_timezone_boundary",
    }
)
REMOVED_INEFFECTIVE_TESTS = frozenset(
    {
        "test_hook_run_task_falls_back_when_core_load_fails",
        "test_on_add_run_task_falls_back_when_core_load_fails",
    }
)
MIGRATED_DIRECT_CONTRACT_TESTS = frozenset(
    {
        "test_config_schema_reports_retired_unknown_and_ineffective_values",
        "test_build_and_cache_hints_routes_scheduler_through_service",
        "test_task_business_calendar_context_selects_and_restores_policy",
        "test_astronomy_preflight_reports_configuration_and_provider_health",
        "test_astronomy_none_event_is_actionable",
        "test_navigator_snapshot_metadata_preserves_typed_chain_identity",
        "test_navigator_sparse_calendar_renders_only_active_months",
        "test_core_render_panel_line_force_rich_kind_skips_panel_line",
        "test_moon_phase_intersection_fails_closed_without_synthetic_date",
        "test_omit_scheduler_failures_do_not_fail_open",
        "test_ui_live_renderer_reveals_timeline_without_highlight",
        "test_completion_parent_guard_uses_persisted_terminal_timestamp",
        "test_taskwarrior_client_preserves_evidence_and_redacts_observation",
        "test_modify_lifecycle_activation_requires_complete_root_identity",
        "test_moon_phase_source_and_filter_compose_with_weekday",
        "test_moon_phase_source_emits_once_per_phase_window",
        "test_occurrence_collection_preserves_prefix_before_date_terminal",
        "test_modify_timeline_marks_omit_evaluation_failures",
        "test_anchor_and_file_tie_preserves_file_description",
        "test_modify_until_past_guard_orders_dst_fold_by_instant",
        "test_ui_live_failure_preserves_rows_for_static_fallback",
        "test_modify_ordinary_transition_failure_rejects_instead_of_noop",
        "test_completion_scheduler_terminal_outcomes_are_not_spawned",
        "test_chain_cap_guards_are_inclusive_at_boundary",
        "test_ui_live_mode_non_tty_falls_back_without_live_control_codes",
        "test_clear_all_caches_env",
        "test_chainid_legacy_reads_do_not_drive_chain_identity",
        "test_anchor_step_preserves_scheduler_exhaustion",
        "test_navigator_surfaces_anchor_projection_failures",
        "test_ui_live_renderer_rejects_dumb_terminal",
        "test_reconcile_evidence_includes_local_child_time_when_formatter_available",
        "test_navigator_projection_preserves_scheduler_terminal_evidence",
        "test_moon_phase_operational_errors_are_actionable",
        "test_yearly_rand_uses_independent_chain_scoped_draws",
        "test_random_weekday_explicit_or_keeps_separate_draws",
        "test_completion_caps_earliest_limit_wins",
        "test_diagnostic_event_renders_to_stderr_and_has_stable_record",
        "test_modify_timeline_marks_projection_failures_instead_of_silent_truncation",
        "test_modify_timeline_preserves_typed_terminal_projection_evidence",
        "test_add_preview_event_collection_counts_only_included_occurrences",
        "test_timeline_completed_rows_place_uuid_before_delta",
        "test_ui_build_rich_panel_preserves_static_layout_and_theme",
        "test_compact_anchor_file_lookup_scans_past_legacy_probe_limit",
        "test_compact_anchor_file_lookup_reports_cursor_exhaustion",
        "test_ui_static_rich_renderer_delegates_to_shared_builder",
        "test_astronomical_season_calculator_contract",
        "test_seasonal_selection_scheduler_windows_and_rollover",
        "test_navigator_uses_task_business_calendar_for_anchor_projection",
        "test_modify_anchor_file_mode_orders_dst_fold_by_instant",
        "test_hook_engine_retains_completion_lifecycle_result_on_runtime_context",
        "test_modify_inclusion_collection_uses_shared_progress_guard",
        "test_modify_until_projection_fails_closed_at_iteration_limit",
        "test_modify_until_projection_reuses_anchor_file_provider",
        "test_integrity_recovery_fault_matrix_fails_closed",
        "test_navigator_resolves_symbolic_anchor_time_offsets",
        "test_add_anchor_file_local_projection_deduplicates_dst_gap",
        "test_merged_anchor_file_provider_carries_context_and_reuses_specs",
        "test_event_provider_preserves_anchor_file_source_description",
        "test_included_provider_reuses_shared_anchor_file_provider",
        "test_included_provider_rebuilds_shared_provider_when_fallback_changes",
        "test_anchor_file_next_occurrence_after_uses_shared_dst_ordering",
        "test_anchor_file_expression_merges_sources_and_applies_group_modifiers",
        "test_file_source_wildcards_are_deterministic_and_star_dot_star_means_all",
        "test_anchor_file_expression_preserves_per_source_times_and_dedupes_matches",
        "test_omit_file_expression_merges_sources_atomically_and_rejects_group_times",
        "test_file_source_symlink_must_remain_inside_configured_directory",
        "test_file_backed_csv_missing_date_column_reports_columns",
        "test_file_backed_empty_or_no_usable_dates_fail_cleanly",
        "test_file_backed_cache_detects_same_size_content_replacement",
        "test_file_backed_cache_uses_metadata_for_hot_reads_and_bounds_lru",
        "test_file_backed_cache_reuses_digest_matches_after_metadata_changes",
        "test_file_backed_resource_limits_reject_oversized_inputs",
        "test_file_source_resource_limits_bound_wildcard_fanout",
        "test_file_date_aggregate_limits_cover_anchor_omit_and_business_calendars",
        "test_seasonal_selection_business_calendar_and_cache_identity",
        "test_astronomical_time_skips_unavailable_candidate_dates",
        "test_cache_load_retries_when_file_is_replaced_during_read",
        "test_core_anchor_preset_unknown_lists_available_names",
        "test_core_omit_preset_unknown_lists_available_names",
        "test_core_preset_recursion_chain_is_deterministic",
        "test_core_nested_preset_display_shows_resolved_leaf",
        "test_anchor_cache_cleans_stale_tmp_files",
        "test_anchor_cache_garbage_collection_prunes_expired_and_overflow",
        "test_cache_metrics_emits_when_enabled",
        "test_diag_log_structured_fields",
        "test_warn_rate_limited_any",
        "test_business_calendar_fingerprint_invalidates_rule_file_and_hint_caches",
        "test_build_local_datetime_dst_gap_and_ambiguous",
        "test_dst_round_trip_noon_preserves_local_date",
        "test_config_support_reports_automatically_discovered_toml_parse_errors",
        "test_config_support_rejects_unsafe_toml_and_reports_reason",
        "test_config_support_distinguishes_empty_missing_and_invalid_candidates",
        "test_integration_mutation_models_enforce_guards_and_postconditions",
        "test_integration_mutation_requests_use_named_typed_payloads",
        "test_integration_outbox_models_enforce_deterministic_identity_and_progress",
        "test_integration_context_resolves_and_validates_invocation_once",
        "test_next_for_and_transient_stall_recovers",
        "test_navigator_uses_nautical_configured_timezone",
        "test_moon_phase_real_astral_boundary_smoke",
        "test_moon_astral_events_preserve_timezone_and_dst",
        "test_moonrise_unavailable_location_fails_closed",
        "test_hook_runtime_retains_module_import_failure_details",
        "test_season_mode_configuration_contract",
        "test_on_modify_loaded_empty_snapshot_prevents_full_timeline_export",
        "test_ui_render_panel_routes_live_mode_without_static_duplicate",
        "test_completion_preflight_stops_on_unavailable_next_lookup",
        "test_next_for_and_no_progress_fails_fast",
        "test_normalize_spec_for_acf_cache_guards",
        "test_shipped_config_keeps_hook_toggles_top_level",
        "test_shipped_config_matches_authoritative_schema",
        "test_core_render_panel_line_mode_uses_panel_line",
        "test_hook_task_runner_handles_nonzero",
        "test_shared_hook_subprocess_runner_preserves_output_and_status",
        "test_hook_task_result_preserves_typed_runner_result",
        "test_core_run_task_tempfiles_fallback_handles_bytes_input",
        "test_roll_apply_has_guard",
        "test_build_and_cache_hints_returns_isolated_cached_payload",
        "test_moon_phase_contradictions_are_rejected",
        "test_core_run_task_tempfiles_accepts_text_input",
        "test_core_run_task_timeout_reports_timeout_with_tempfiles",
        "test_core_run_task_result_exposes_typed_metadata",
        "test_core_run_task_nonzero_retries_use_expected_backoff",
        "test_core_run_task_does_not_retry_ordinary_nonzero",
        "test_config_exposes_anchor_file_dir",
        "test_on_add_compact_anchor_preview_requests_one_occurrence",
        "test_omit_file_modifiers_roll_dates_and_carry_descriptions",
        "test_omit_file_modifiers_support_negative_day_offsets",
        "test_omit_file_modifiers_apply_even_when_base_file_is_cached",
        "test_omit_file_modifiers_reject_time_modifiers",
        "test_sanitize_task_strings_removes_controls",
        "test_navigator_empty_snapshot_is_a_valid_empty_chain",
        "test_navigator_and_query_share_task_chain_facts",
        "test_navigator_snapshot_exposes_deterministic_typed_view",
        "test_navigator_calendar_view_is_immutable_and_serializable",
        "test_navigator_chain_summary_is_immutable_and_serializable",
        "test_navigator_chain_choice_is_immutable_and_serializable",
        "test_navigator_change_row_is_immutable_and_serializable",
        "test_navigator_task_detail_view_is_immutable_and_serializable",
        "test_navigator_projection_view_is_immutable_and_serializable",
        "test_navigator_trace_view_is_immutable_and_serializable",
        "test_navigator_analysis_view_aggregates_typed_sections",
        "test_moon_phase_anchor_grammar_normalizes_canonical_names",
        "test_astronomy_profile_requires_explicit_timezone",
        "test_moon_phase_resolver_uses_circular_phase_distance",
        "test_moon_phase_resolver_uses_documented_phase_bands",
        "test_cp_duration_parser_and_dst_preserve_whole_days",
        "test_cp_sequence_link_boundary_contract",
        "test_cp_random_and_jitter_are_deterministic_per_link_and_bounded",
        "test_cp_random_seed_is_chain_scoped_and_normalized",
        "test_year_day_ordinals_validate_strictly",
        "test_year_day_ordinals_expand_and_schedule",
        "test_iso_week_ordinals_expand_across_year_boundaries",
        "test_iso_week_ordinals_validate_strictly",
        "test_year_ordinals_compose_with_weekdays_or_and_modifiers",
        "test_iso_week_interval_uses_iso_year_buckets",
        "test_year_ordinals_filter_random_and_omit_candidates",
        "test_year_ordinals_positional_acf_and_cache_round_trip",
        "test_year_ordinals_documented_examples",
        "test_omit_file_name_rejects_paths",
        "test_omit_file_csv_header_parsing_is_order_independent_and_dedupes",
        "test_omit_file_csv_description_mapping_is_order_independent",
        "test_anchor_file_name_rejects_paths",
        "test_anchor_file_spec_parses_time_and_negative_offset",
        "test_anchor_file_spec_parses_bounded_time_window",
        "test_anchor_file_spec_rejects_unpadded_times",
        "test_anchor_file_composable_schedule_rejects_empty_members",
        "test_anchor_file_occurrence_provider_supports_lazy_next_after",
        "test_anchor_file_occurrence_provider_caches_expanded_specs",
        "test_anchor_file_occurrence_provider_advances_cached_lookup_cursor",
        "test_anchor_file_provider_uses_binary_search_for_nonmonotonic_cursor",
        "test_anchor_file_occurrence_provider_sorts_dst_normalized_candidates",
        "test_anchor_file_provider_retries_after_failed_load",
        "test_anchor_file_provider_keeps_description_for_overnight_slots",
        "test_anchor_file_provider_merges_duplicate_source_descriptions",
        "test_anchor_file_provider_preserves_dst_fold_descriptions",
        "test_anchor_file_provider_orders_dst_fallback_by_instant",
        "test_anchor_file_provider_rejects_incomparable_datetimes",
        "test_included_provider_bounds_anchor_file_omission_scan",
        "test_anchor_inclusion_scheduler_propagates_internal_errors",
        "test_anchor_file_omit_evaluation_failures_propagate",
        "test_recurrence_evaluator_loads_omit_file_without_text_rule",
        "test_recurrence_evaluator_loads_omit_file_dates_and_descriptions_once",
        "test_domain_scheduler_parity_across_operational_consumers",
        "test_recurrence_evaluator_shadow_parity_time_matrix",
        "test_recurrence_evaluator_shadow_parity_dst_and_business_calendar",
        "test_modify_timeline_uses_explicit_recurrence_identity",
        "test_modify_hook_uses_explicit_recurrence_identity",
        "test_add_preview_uses_explicit_recurrence_identity",
        "test_random_time_window_dst_projection_is_deterministic",
        "test_random_time_window_composition_and_anchor_file_guidance",
        "test_position_selection_parses_arbitrary_ordinals",
        "test_position_selection_rejects_invalid_tokens_and_bounds",
        "test_position_selection_candidate_capacity_bounds",
        "test_position_selection_candidate_capacity_bounds_are_sound",
        "test_position_selection_rejects_only_fully_impossible_candidates",
        "test_position_selection_semantic_advice",
        "test_position_selection_period_boundaries",
        "test_position_selection_internal_evaluator",
        "test_position_selection_internal_evaluator_validation",
        "test_position_selection_next_date_jumps_periods",
        "test_position_selection_candidate_cache_identity",
        "test_position_selection_public_monthly_parser_validation",
        "test_position_selection_public_monthly_scheduler",
        "test_position_selection_post_modifiers_parser_and_scheduler",
        "test_position_selection_public_period_scopes_validation",
        "test_position_selection_public_period_scopes_scheduler",
        "test_position_selection_documented_examples_and_feedback",
        "test_anchor_omit_rejects_time_modifiers",
        "test_anchor_omit_next_after_expr_skips_matching_dates",
        "test_anchor_omit_next_after_expr_skips_omit_file_dates",
        "test_anchor_omit_grouped_list_plus_expr_applies_filter_to_all_items",
        "test_anchor_omit_business_day_roll_matches_rolled_date",
        "test_anchor_omit_positive_day_offset_matches_shifted_date",
        "test_file_source_expression_flattens_groups_and_rejects_unsafe_patterns",
        "test_native_until_carry_descriptions",
        "test_native_until_validation_orders_dst_fold_by_instant",
        "test_native_until_exact_carry_orders_dst_fold_by_instant",
        "test_schedule_and_completion_use_shared_datetime_comparator",
        "test_local_datetime_full_day_gap_shifts_to_next_valid_wall_time",
        "test_public_datetime_comparator_preserves_dst_fold_and_provider_alias",
        "test_recurrence_fingerprint_is_canonical_and_mutation_sensitive",
        "test_effective_config_snapshot_isolated_and_provenanced",
        "test_hot_config_fingerprint_avoids_filesystem_stat",
        "test_hook_bootstrap_numeric_env_parsing_is_bounded",
        "test_recurrence_spec_normalizes_task_fields_and_context",
        "test_last_weekday",
        "test_panel_diagnostics_warns_for_missing_env_config",
        "test_runtime_manifest_covers_lazy_panel_colour_module",
        "test_legacy_exit_flow_modules_are_not_runtime_owned",
        "test_on_add_preview_warns_when_anchor_uses_utc_fallback",
        "test_panel_diagnostics_warns_for_empty_file_sources",
        "test_doctor_reports_uda_alias_configuration",
        "test_doctor_reports_live_panel_configuration_health",
        "test_doctor_reports_authoritative_config_schema_findings",
        "test_doctor_text_timezone_summary",
        "test_doctor_text_large_history_is_actionable_and_compact",
        "test_doctor_text_groups_historical_findings_across_chains",
        "test_doctor_reports_missing_timezone_data",
        "test_doctor_reports_missing_timezone_configuration",
        "test_doctor_reports_astronomy_preflight_health",
        "test_doctor_reports_season_backend_and_astronomical_events",
        "test_doctor_reports_matching_config_drift",
        "test_doctor_reports_missing_navigator_dependencies",
        "test_operator_context_discovers_taskdata_once",
        "test_operator_presentation_has_no_mutation_dependencies",
        "test_lifecycle_candidate_reads_support_bounded_and_full_audit_modes",
        "test_chain_integrity_warnings_detects_issues",
        "test_chain_health_advice_coach_healthy_streak",
        "test_chain_health_advice_coach_low_ontime_issue",
        "test_chain_health_advice_clinical_drift_and_style_normalization",
        "test_core_explicit_facade_all_contains_supported_symbols",
        "test_all_golden_tests_are_registered",
        "test_query_cli_emits_one_json_document_for_invalid_request",
        "test_query_emit_compact_json_preserves_unicode_and_budget",
        "test_integrity_consumers_share_report_components",
        "test_task_command_classifies_boundary_failures",
        "test_task_command_retries_only_opted_in_locks",
        "test_fixed_season_calendar_boundaries",
        "test_fixed_season_calendar_finds_active_or_next_window",
        "test_fixed_season_calendar_rejects_invalid_contract_values",
        "test_fixed_season_calendar_supports_southern_hemisphere_profile",
        "test_seasonal_selection_parser_contract",
        "test_seasonal_selection_acf_round_trip",
        "test_astronomical_season_support_boundaries_are_mode_and_hemisphere_aware",
        "test_astronomical_season_local_date_and_overflow_contract",
        "test_generic_seasonal_selection_scheduler_and_round_trip",
        "test_seasonal_selection_scheduler_post_modifiers",
        "test_seasonal_selection_boundary_and_overflow_contract",
        "test_seasonal_selection_semantic_guard",
        "test_default_business_calendar_operations_characterization",
        "test_business_calendar_config_normalizes_immutable_definitions",
        "test_business_calendar_config_rejects_ambiguous_or_unstable_rules",
        "test_business_calendar_policy_flows_through_scheduler_paths",
        "test_business_calendar_displacement_capture_is_shift_only",
        "test_business_calendar_policy_flows_through_file_modifiers",
        "test_business_calendar_config_resolves_rules_files_and_omissions",
        "test_anchor_file_occurrences_expand_bounded_time_window",
        "test_anchor_file_occurrences_expand_random_time_window_with_context",
        "test_anchor_file_occurrence_provider_exposes_typed_values",
        "test_anchor_file_occurrences_expand_overnight_time_window",
        "test_anchor_file_occurrences_expand_composable_time_schedule",
        "test_anchor_file_loader_transforms_dates_and_carries_descriptions",
        "test_anchor_file_next_occurrence_after_uses_task_level_time",
        "test_provider_contract_advertises_only_certified_capabilities",
        "test_occurrence_provider_adapters_preserve_stream_metadata",
        "test_occurrence_provider_rejects_malformed_callback_payloads",
        "test_occurrence_providers_reject_non_advancing_values",
        "test_occurrence_values_reject_inconsistent_fields",
        "test_occurrence_event_provider_requires_boolean_omitted_flag",
        "test_occurrence_collection_inclusive_cursor_steps_back_by_instant",
        "test_occurrence_collection_fails_closed_on_invalid_values_and_exhaustion",
        "test_occurrence_collection_enforces_cursor_progress_and_timezone_consistency",
        "test_anchor_occurrence_provider_exposes_typed_values_and_lazy_lookup",
        "test_anchor_file_cursor_reuse_matches_fresh_provider_reference",
        "test_anchor_file_batch_generation_matches_repeated_reference_lookups",
        "test_occurrence_provider_rejects_dst_fallback_backward_progress",
        "test_time_window_parser_expands_inclusive_exact_boundary",
        "test_time_window_parser_rejects_unsafe_or_ambiguous_ranges",
        "test_time_window_slot_limit_uses_shared_resource_policy",
        "test_time_window_parser_accepts_compound_minute_intervals",
        "test_time_window_parser_accepts_hour_only_and_mixed_endpoints",
        "test_random_time_window_parser_selects_deterministic_bucketed_slots",
        "test_composable_time_schedule_deduplicates_overlaps_and_boundaries",
        "test_time_window_parser_rejects_unpadded_or_out_of_range_hour_endpoints",
        "test_time_window_partition_rounding_preserves_boundaries",
        "test_composable_time_schedule_enforces_aggregate_slot_limit",
        "test_description_alias_parser_extracts_short_udas",
        "test_description_alias_parser_avoids_prose_and_rejects_duplicates",
        "test_quarter_selector_mode_characterization",
        "test_quarter_selector_mode_rejections",
        "test_term_quarter_rewrite_mode_characterization",
        "test_quarter_spec_rewrite_characterization",
        "test_rewrite_quarters_in_context_characterization",
        "test_time_window_parser_accepts_even_partition_counts",
        "test_random_time_window_flows_through_anchor_parser_and_resolver",
        "test_hour_only_time_lists_normalize_across_anchor_and_anchor_file",
        "test_composable_time_schedule_unions_windows_and_clock_slots",
        "test_composable_time_schedule_rejects_non_numeric_members",
        "test_composable_time_schedule_rejects_empty_members",
        "test_time_window_grammar_expands_and_round_trips_through_acf",
        "test_grouped_time_window_metadata_distributes_to_each_branch",
        "test_composable_schedule_preserves_offsets_and_group_validation",
        "test_time_window_natural_language_uses_bounded_interval",
        "test_random_time_metadata_rejects_contradictory_cached_shapes",
        "test_cached_time_window_metadata_rejects_slot_drift",
        "test_cached_random_time_metadata_rejects_invalid_specs",
        "test_cached_time_schedule_metadata_rejects_slot_drift",
        "test_anchor_parse_term_explosion_guard",
        "test_parser_satisfiability_agrees_with_scheduler",
        "test_quarters_window",
        "test_quarter_alias_unambiguous_month_selectors",
        "test_astronomical_event_vocabulary_is_shared_by_parser_and_runtime",
        "test_weekly_and_unsat",
        "test_expansion_helpers_characterization",
        "test_nth_weekday_range",
        "test_lint_anchor_expr_characterization",
        "test_monthly_support_helpers_characterization",
        "test_leap_year_29feb",
        "test_anchor_expr_length_limit",
        "test_lint_formats",
        "test_anchor_grouped_list_plus_expr_applies_filter_to_all_items",
        "test_lint_grouped_list_plus_expr_matches_current_grammar",
        "test_unsat_hint_uses_yearly_alias_for_month_name_examples",
        "test_inline_time_mods_split_ok",
        "test_weekly_trailing_time_modifier_applies_to_whole_list",
        "test_same_day_next_weekday_roll_moves_forward_one_week",
        "test_same_day_prev_weekday_roll_moves_back_one_week",
        "test_next_weekday_roll_cross_year_date_still_matches_expression",
        "test_weekly_multi_days_every_2weeks_spacing_and_days",
        "test_monthly_valid_months_m2_5th_mon",
        "test_monthly_valid_months_m2_5th_mon_upcoming_within_valid_months",
        "test_leap_year_29feb_upcoming_only_on_leap_year",
        "test_rand_with_year_window_filtering",
        "test_weekly_rand_N_gate_spacing",
        "test_deterministic_randomness",
        "test_business_day_modifiers",
        "test_weekly_rand_is_chain_scoped_and_deterministic",
        "test_monthly_rand_year_intersection_is_chain_scoped",
        "test_random_weekday_list_is_one_grouped_draw",
        "test_group_time_modifier_distributes_to_all_branches",
        "test_group_time_modifier_supports_multiple_times",
        "test_group_astronomical_time_offset_distributes_to_all_branches",
        "test_group_date_modifiers_distribute_across_or_branches",
        "test_group_modifiers_reject_ambiguous_combinations",
        "test_counted_random_selects_unique_dates_per_period",
        "test_counted_random_is_deterministic_chain_scoped_and_constrained",
        "test_counted_random_omit_redraws_from_remaining_pool",
        "test_counted_random_cadence_time_and_canonical_round_trip",
        "test_edge_cases",
        "test_anchor_date_calculations",
        "test_heads_with_slashN_parse_ok",
        "test_random_anchor_cross_chain_matrix",
        "test_validate_year_tokens_in_dnf_characterization",
        "test_parse_y_token_characterization",
        "test_complex_dnf_expressions",
        "test_interval_patterns",
        "test_yearly_month_aliases_and_ranges",
        "test_business_day_bd_skip_semantics",
        "test_guard_commas_between_atoms_after_mods_fatal",
        "test_heads_with_slashN_parse_ok_again",
        "test_monthname_and_numeric_equivalence",
        "test_yearly_month_names",
        "test_rand_with_year_window",
        "test_weekly_rand_N_gate",
        "test_monthly_and_yearly_random_intervals_scale_and_exhaust",
        "test_weekly_random_intervals_scale_and_exhaust",
        "test_time_splitting_per_atom",
        "test_weekly_multi_days_and_every_2weeks",
        "test_symbolic_anchor_time_modifiers_accept_supported_events",
        "test_rand_bucket_signature_characterization",
        "test_pick_hhmm_from_dnf_for_positive_day_offset_shifted_date",
        "test_atom_matches_on_positive_day_offset_shifted_date",
        "test_parse_anchor_expr_fuzz_inputs",
        "test_anchor_parse_validate_fuzz_no_unexpected_exceptions",
        "test_anchor_validate_roundtrip_preserves_next_occurrence",
        "test_anchor_parse_deep_nesting_guard",
        "test_anchor_validate_rejects_legacy_tuple_error_payload",
        "test_rand_determinism_with_seed",
        "test_next_after_expr_branch_characterization",
        "test_anchor_normalization_is_semantically_idempotent",
        "test_anchor_expression_characterization_matrix",
        "test_weeks_between_iso_boundary",
        "test_short_uuid_invalid_inputs",
        "test_coerce_int_bounds",
        "test_next_after_atom_with_mods_characterization",
        "test_satisfiability_helpers_characterization",
        "test_month_alias_in_monthly_anchor_suggests_yearly_anchor",
        "test_warn_once_per_day_stamp_written",
        "test_warn_once_per_day_no_diag_silent",
        "test_warn_once_per_day_any_no_diag_silent",
        "test_cache_consistency",
        "test_chain_max_parser_requires_positive_integer",
        "test_core_resolve_task_data_context_rejects_parent_traversal_segments",
        "test_core_config_paths_rejects_parent_traversal_in_env",
        "test_core_config_paths_trust_override_allows_parent_traversal_in_env",
        "test_core_resolve_task_data_context_precedence",
        "test_core_resolve_task_data_context_rejects_unsafe_world_writable_dir",
        "test_core_resolve_task_data_context_trust_override_allows_explicit_dir",
        "test_occurrence_cursor_makes_lookup_semantics_explicit",
        "test_occurrence_cursor_keeps_adjacent_weekday_occurrences",
        "test_typed_occurrence_outcomes_preserve_found_invalid_and_absent_states",
        "test_typed_occurrence_outcomes_preserve_terminal_evidence",
        "test_typed_occurrence_outcomes_fail_closed_for_mutation",
        "test_typed_occurrence_outcomes_define_compact_presentation_summary",
        "test_evaluation_session_is_task_scoped_and_fingerprint_bound",
        "test_scheduler_service_is_one_typed_occurrence_entry_point",
        "test_scheduler_trace_is_disabled_bounded_and_redacted",
        "test_scheduler_cross_path_preserves_terminal_evidence",
        "test_occurrence_range_request_validates_context_bounds_and_policy",
        "test_occurrence_range_request_exposes_omission_provenance",
        "test_occurrence_range_request_wraps_unavailable_and_invalid_failures",
        "test_scheduler_conformance_isolated_under_shuffled_session_order",
        "test_hint_builder_does_not_convert_typed_failure_to_empty_hints",
        "test_recurrence_evaluator_events_between_preserves_terminal_evidence",
        "test_scheduler_generated_recurrence_matrix_is_monotonic_and_deterministic",
        "test_scheduler_parity_harness_compares_legacy_callback_only_in_tests",
        "test_scheduler_parity_matrix_covers_context_sensitive_rules",
    }
)


class GoldenRegistryIntegrityTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.golden = importlib.import_module(GOLDEN_MODULE)

    def test_registered_functions_are_unique_and_callable(self):
        registered = [*self.golden.TESTS, *self.golden.DEEP_TESTS]
        names = [fn.__name__ for fn in registered]
        self.assertEqual(len(names), len(set(names)), "golden registry contains duplicates")
        self.assertTrue(all(callable(fn) for fn in registered))
        self.assertTrue(all(name.startswith("test_") for name in names))

    def test_live_top_level_tests_are_registered_or_explicitly_retired(self):
        registered = {
            fn.__name__ for fn in (*self.golden.TESTS, *self.golden.DEEP_TESTS)
        }
        top_level = {
            name
            for name, value in vars(self.golden).items()
            if name.startswith("test_") and callable(value)
        }
        self.assertEqual(
            top_level - registered,
            set(RETIRED_CHARACTERIZATION_TESTS),
            "unregistered golden tests must be migrated or explicitly retired",
        )
        self.assertFalse(RETIRED_CHARACTERIZATION_TESTS & registered)

    def test_migrated_direct_contracts_are_absent_from_golden_runner(self):
        registered = {
            fn.__name__ for fn in (*self.golden.TESTS, *self.golden.DEEP_TESTS)
        }
        top_level = {
            name
            for name, value in vars(self.golden).items()
            if name.startswith("test_") and callable(value)
        }
        self.assertFalse(MIGRATED_DIRECT_CONTRACT_TESTS & registered)
        self.assertFalse(MIGRATED_DIRECT_CONTRACT_TESTS & top_level)
        self.assertFalse(MIGRATED_DIRECT_CONTRACT_TESTS & RETIRED_CHARACTERIZATION_TESTS)

    def test_removed_ineffective_tests_stay_absent(self):
        registered = {
            fn.__name__ for fn in (*self.golden.TESTS, *self.golden.DEEP_TESTS)
        }
        top_level = {
            name
            for name, value in vars(self.golden).items()
            if name.startswith("test_") and callable(value)
        }
        self.assertFalse(REMOVED_INEFFECTIVE_TESTS & registered)
        self.assertFalse(REMOVED_INEFFECTIVE_TESTS & top_level)

    def test_registry_inventory_counts_match_documented_snapshot(self):
        registered = [*self.golden.TESTS, *self.golden.DEEP_TESTS]
        top_level = [
            value
            for name, value in vars(self.golden).items()
            if name.startswith("test_") and callable(value)
        ]
        self.assertEqual(len(top_level), 444)
        self.assertEqual(len(registered), 432)
        self.assertEqual(len(RETIRED_CHARACTERIZATION_TESTS), 12)
        self.assertEqual(len(MIGRATED_DIRECT_CONTRACT_TESTS), 437)


if __name__ == "__main__":
    unittest.main()
